use_frameworks!

target 'SYAuthorizationTool_Example' do
  pod 'SYAuthorizationTool', :path => '../'

  target 'SYAuthorizationTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
